regex:
  address: !ruby/regexp /^(?:\W+／)?(?:■.*：\s?)?(?:【[^【]+?】)?(?:＜[^＜]*＞)?(?:.+：)?(?:◎.+?／)?〒?(\d+-\d+)?\s?(?:＜[^＜]*＞)?(?:【[^【]*】)?(?:.+：)?(?:\[[^\[]*\])?(?:（[^（]*）)?(?:\W+／)?(北海道|青森県|岩手県|秋田県|山形県|宮城県|福島県|新潟県|栃木県|群馬県|茨城県|埼玉県|千葉県|東京都|神奈川県|山梨県|静岡県|長野県|富山県|石川県|福井県|岐阜県|愛知県|三重県|奈良県|和歌山県|滋賀県|京都府|大阪府|兵庫県|岡山県|広島県|鳥取県|島根県|山口県|香川県|徳島県|愛媛県|高知県|福岡県|佐賀県|長崎県|熊本県|大分県|宮崎県|鹿児島県|沖縄県)?\s?(\W+?[市|区|村|町])?(\W+[0-9一-十]*丁目[0-9一-十]+番地の+[0-9一-十]+|\S*[0-9一-十]*丁目[0-9一-十]*番[0-9一-十]*[号|地]?[0-9一-十]*|\S+[0-9一-十]*丁目[0-9一-十]*-?[0-9一-十]*|\W+[0-9一-十]*条西[0-9一-十]+丁目[0-9一-十]*-?[0-9一-十]*|\W+[0-9一-十]*条西[0-9一-十]*-?[0-9一-十]*-?[0-9一-十]*|\W*町[0-9一-十]*[番|地|の]+[0-9一-十]*-?[0-9一-十]*号?|\W+町[下|山|口]+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+|\W+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+-[0-9一-十]+Ｆ?B?|\W+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+Ｆ?B?|\W+[0-9一-十]+-[0-9一-十]+-?[0-9一-十]*Ｆ?B?|\W+?[0-9一-十]+[番|地]+[0-9一-十]+号?|\W+?[0-9一-十]+[番|地]+|\W+町+\W+[0-9一-十]+号?[0-9一-十]*-?[0-9一-十]*-?[0-9一-十]*|\W+町[0-9一-十]+)?\s?(?:【[^【]+?】.*)?(?:.+?：)?(?:◎.+?／.*)?(.*)/
  is_address: !ruby/regexp /^〒?(\d+-\d+)?\s?(北海道|青森県|岩手県|秋田県|山形県|宮城県|福島県|新潟県|栃木県|群馬県|茨城県|埼玉県|千葉県|東京都|神奈川県|山梨県|静岡県|長野県|富山県|石川県|福井県|岐阜県|愛知県|三重県|奈良県|和歌山県|滋賀県|京都府|大阪府|兵庫県|岡山県|広島県|鳥取県|島根県|山口県|香川県|徳島県|愛媛県|高知県|福岡県|佐賀県|長崎県|熊本県|大分県|宮崎県|鹿児島県|沖縄県)?\s?(\W+?[市|区|村|町])?(\W+[0-9一-十]*丁目[0-9一-十]+番地の+[0-9一-十]+|\S*[0-9一-十]*丁目[0-9一-十]*番[0-9一-十]*[号|地]?|\S+[0-9一-十]*丁目[0-9一-十]*-?[0-9一-十]*|\W+[0-9一-十]*条西[0-9一-十]+丁目[0-9一-十]*-?[0-9一-十]*|\W+[0-9一-十]*条西[0-9一-十]*-?[0-9一-十]*-?[0-9一-十]*|\W*町[0-9一-十]*[番|地|の]+[0-9一-十]*号?|\W+町[下|山|口]+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+|\W+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+-[0-9一-十]+Ｆ?B?|\W+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+Ｆ?B?|\W+[0-9一-十]+-[0-9一-十]+-?[0-9一-十]*Ｆ?B?|\W+?[0-9一-十]+[番|地]+[0-9一-十]+号?|\W+?[0-9一-十]+[番|地]+|\W+町+\W+[0-9一-十]+号?[0-9一-十]*-?[0-9一-十]*-?[0-9一-十]*|\W+町[0-9一-十]+)?/
  once_address: !ruby/regexp /^(?:\W+／)?(?:■.*：\s?)?(?:【[^【]+?】)?(?:＜[^＜]*＞)?(?:.+：)?(?:◎.+?／)?〒?(\d+-\d+)?\s?(?:＜[^＜]*＞)?(?:【[^【]*】)?(?:.+：)?(?:\[[^\[]*\])?(?:（[^（]*）)?(?:\W+／)?(北海道|青森県|岩手県|秋田県|山形県|宮城県|福島県|新潟県|栃木県|群馬県|茨城県|埼玉県|千葉県|東京都|神奈川県|山梨県|静岡県|長野県|富山県|石川県|福井県|岐阜県|愛知県|三重県|奈良県|和歌山県|滋賀県|京都府|大阪府|兵庫県|岡山県|広島県|鳥取県|島根県|山口県|香川県|徳島県|愛媛県|高知県|福岡県|佐賀県|長崎県|熊本県|大分県|宮崎県|鹿児島県|沖縄県)?\s?(\W+?[市|区|村|町])?(\W+[0-9一-十]*丁目[0-9一-十]+番地の+[0-9一-十]+|\S*[0-9一-十]*丁目[0-9一-十]*番[0-9一-十]*[号|地]?[0-9一-十]*|\S+[0-9一-十]*丁目[0-9一-十]*-?[0-9一-十]*|\W+[0-9一-十]*条西[0-9一-十]+丁目[0-9一-十]*-?[0-9一-十]*|\W+[0-9一-十]*条西[0-9一-十]*-?[0-9一-十]*-?[0-9一-十]*|\W*町[0-9一-十]*[番|地|の]+[0-9一-十]*-?[0-9一-十]*号?|\W+町[下|山|口]+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+|\W+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+-[0-9一-十]+Ｆ?B?|\W+[0-9一-十]+-[0-9一-十]+-[0-9一-十]+Ｆ?B?|\W+[0-9一-十]+-[0-9一-十]+-?[0-9一-十]*Ｆ?B?|\W+?[0-9一-十]+[番|地]+[0-9一-十]+号?|\W+?[0-9一-十]+[番|地]+|\W+町+\W+[0-9一-十]+号?[0-9一-十]*-?[0-9一-十]*-?[0-9一-十]*|\W+町[0-9一-十]+)?\s?(?:【[^【]+?】.*)?(?:.+?：)?(?:◎.+?／.*)?()/

  town: !ruby/regexp /\d*-\d*-?\d*/
  bracket: !ruby/regexp /【\S*】/
  script: !ruby/regexp /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/
agent_alias: Mac Safari
record_limit: 50
start_from_record: 0
special_word:
  number_array: [["０", "0"], ["１", "1"], ["２", "2"], ["３", "3"], ["４", "4"], ["５", "5"], ["６", "6"], ["７", "7"], ["８", "8"], ["９", "9"], ["/", "／"], ["－", "-"], ["　", " "], ["F", "Ｆ"], ["(", "（"], [")", "）"]]
  pref_array: ["市", "区"]
  bracket: 【
  divide: ／
  postal: 〒
title_jap:
  address: 所在地
  job_type: 職種
  category: 業種
  job_info: 仕事内容
  requirement: 対象となる方
  work_address: 勤務地
  work_time: 勤務時間
  salary: 給与
  treatment: 待遇・福利厚生
  holiday: 休日・休暇
text_jap:
  next: 次へ